spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:deneb
    username: sa
    password: ''
    name: deneb

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true